CURRENCY_CONVERTER_API_KEY = 'fgBmdVrkb6a5cAwZju4kjtQfeK9ftkiC'

element_name_to_field_name = {
  "": "ID",
  "product_type": "Type",
  "": "SKU",
  "product_title": "Name",
  "": "Published",
  "": "Is featured?",
  "": "Visibility in catalog",
  "": "Short description",
  "product_description": "Description",
  "": "Date sale price starts",
  "": "Date sale price ends",
  "": "Tax status",
  "": "Tax class",
  "": "In stock?",
  "product_stock_number": "Stock",
  "": "Low stock amount",
  "": "Backorders allowed?",
  "": "Sold individually?",
  "": "Weight(kg)",
  "": "Length(cm)",
  "": "Width(cm)",
  "": "Height(cm)",
  "": "Allow customer reviews?",
  "": "Purchase note",
  "product_sale_price": "Sale price",
  "product_regular_price": "Regular price",
  "": "Categories",
  "": "Tags",
  "": "Shipping class",
  "product_image_urls": "Images",
  "": "Download limit",
  "": "Download expiry days",
  "": "Parent",
  "": "Grouped products",
  "": "Upsells",
  "": "Cross-sells",
  "": "External URL",
  "": "Button text",
  "": "Position",
  
  "product_brand": "Brand", # Brand
  "product_thumpnail_image_urls": "",
}